# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13maME0Gfbc0aTFdbqtkWcyEFBtj9QK2F
"""

import numpy as np
import pandas as pd

def grad_func(x,y):
  m_curr = b_curr = 0
  it = 1000000
  n = len(x)
  for i in range(it):
    y_pred = m_curr * x + b_curr
    cost = (1/n) * sum([val**2 for val in (y-y_pred)])
    md = -(2/n) * sum(x * (y - y_pred))
    bd = -(2/n) * sum(y - y_pred)
    m_curr = m_curr - 0.0001 * md
    b_curr = b_curr - 0.0001 * bd
    if(i%10000 == 0):
      print ("m {}, b {}, cost {} iteration {}".format(m_curr,b_curr,cost, i))

  return m_curr, b_curr

if __name__ == "__main__":
  df = pd.read_csv("/content/test_scores.csv")
  x = np.array(df.math)
  y = np.array(df.cs)
  m, b = grad_func(x,y)
  print ("m {}, b {}".format(m,b))
