# -*- coding: utf-8 -*-
"""Exercise 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UE9iRqpmG567-FViEOeeyz7PI1fsRjMB
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris

dir(iris)

import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df

dof = pd.DataFrame(iris.target, columns=['species'])
dof

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr.predict([[6.3,	2.5,	5.0	,1.9]])

y_predicted = lr.predict(X_test)

y_test

lr.score(X_test, y_test)

from sklearn.metrics import confusion_matrix
yo = confusion_matrix(y_test, y_predicted)
yo

import seaborn as sns
sns.heatmap(yo, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')