# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeDqozFrsImkBaADScrN3o5WJFS_zMpb
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

df = pd.read_csv('/content/carprices (1).csv')

df.head()

import matplotlib.pyplot as plt
plt.scatter(df['Mileage'],df['Sell Price($)'])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['Mileage','Age(yrs)']],df['Sell Price($)'],test_size=0.2,random_state=10)

x_train

model = lr.fit(x_train,y_train)

model.predict(x_test)

y_test

model.score(x_test,y_test)