# -*- coding: utf-8 -*-
"""Exercise_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1xLPUY37HllaiCYOnL5XEvFvKQlSS95
"""

import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
!pip install word2number
from word2number import w2n

df= pd.read_csv('/content/hiring.csv')
df

import math
median_test= math.floor(df['test_score(out of 10)'].median())
median_test

df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test)
df

df.experience= df.experience.fillna('zero')
df

df.experience = df.experience.apply(w2n.word_to_num)
df

reg=linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

reg.coef_

reg.intercept_

reg.predict([[2,9,6]])

reg.predict([[12,10,10]])