# -*- coding: utf-8 -*-
"""Exercise 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lv1U6lvspHJrczN7TYQsHlo9cx_o9sN
"""

import pandas as pd
df = pd.read_csv('/content/carprices.csv')
df

dummy = pd.get_dummies(df['Car Model'])
dummy

ndata = pd.concat([df,dummy],axis='columns')
ndata

fdata = ndata.drop(['Car Model','Mercedez Benz C class'],axis='columns')
fdata

from sklearn import linear_model
model = linear_model.LinearRegression()

x= fdata.drop('Sell Price($)',axis='columns')
x

y = fdata['Sell Price($)']
y

model.fit(x,y)

model.predict([[45000,4,0,0]])

model.predict([[86000,7,0,1]])

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
aeo= df
aeo['Car Model'] =le.fit_transform(df['Car Model'])
aeo

aeo.shape

m= pd.DataFrame(m, columns=['Car Model', 'Mileage', 'Age(yrs)'])
m

n= df[[ 'Sell Price($)']].values
n

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
column_transformer = ColumnTransformer(
    transformers=[
        ('category_ohe', OneHotEncoder(), ['Car Model'])
    ],
    remainder='passthrough'
)

transformed_data = column_transformer.fit_transform(m)
transformed_data

X = transformed_data[:, 1:]
X

model.fit(X,n)

model.predict([[2,0,45000,4]])
