# -*- coding: utf-8 -*-
"""Exercise 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrosN60LG_T0OQQhYlT-5x0J2h6Ng3fG
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/titanic.csv")
df.head()

df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

input = df.drop('Survived',axis='columns')
target = df['Survived']

input.head()

target.head()

from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()

input['Sex_n'] = le_sex.fit_transform(input['Sex'])
input.head()

input['Age'] = input['Age'].fillna(input['Age'].mean())
input.head(10)

input.drop('Sex',axis='columns',inplace=True)
input.head()

from sklearn import tree
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(input,target,test_size=0.2)
tr = tree.DecisionTreeClassifier()
tr.fit(x_train,y_train)

tr.predict([[3,22,1,7.2500]])

tr.score(input,target)