# -*- coding: utf-8 -*-
"""Exercise 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWGGANnqJ89Pn4bAw1UwYxrhPGMne5nZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/HR_comma_sep.csv')
df

pd.crosstab(df.salary,df.left).plot(kind='bar')

pd.crosstab(df.Department,df.left).plot(kind='bar')

x_first = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
y = df[['left']]

yo = pd.get_dummies(x_first['salary'])
x = pd.concat([x_first,yo],axis='columns')
x.drop('salary',axis='columns',inplace=True)
x

from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.2)

x_test.head()

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

lr.predict(x_test)

lr.score(x_test,y_test)
