# -*- coding: utf-8 -*-
"""Exercise 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBSEbxjmzbiUry52s1E_60h57j8ltsd6
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

import pandas as pd
import numpy as np
lr = load_iris()
df = pd.DataFrame(lr.data, columns=lr.feature_names)
df

cvs = cross_val_score(SVC(),lr.data, lr.target)
cvs

np.average(cvs)

cvs = cross_val_score(RandomForestClassifier(n_estimators=40), lr.data, lr.target)
cvs

np.average(cvs)

cvs = cross_val_score(LogisticRegression(), lr.data, lr.target)
cvs

np.average(cvs)

cvs = cross_val_score(DecisionTreeClassifier(), lr.data, lr.target)
cvs

np.average(cvs)

"""##So The best one is LogisticRegression one :)"""