# -*- coding: utf-8 -*-
"""Exercise 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGCOEaaXeL93Gk_cvFtFKIse_yrHv1-P
"""

import pandas as pd
from sklearn.datasets import load_iris
lr = load_iris()
df = pd.DataFrame(lr.data, columns=lr.feature_names)
df['target'] = lr.target
df.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df.target, test_size=0.2)

len(X_test)

len(X_train)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=20)
rf.fit(X_train,y_train)

rf.score(X_test,y_test)

rf_predicted = rf.predict(X_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, rf_predicted)

from seaborn import heatmap
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, rf_predicted)
plt.figure(figsize=(10,7))
heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')