# -*- coding: utf-8 -*-
"""Lec 1 machine learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFxi3gAe1dup2POj34GDHOROWQGB8wSY

#Importing Necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

"""#Reading the csv file and ploting the graph"""

df = pd.read_csv("/content/canada_per_capita_income.csv")

plt.xlabel('Year')
plt.ylabel('Per capita income(US$)')
plt.scatter(df.year,df.pci, color='green',marker='*')

"""#Making object of regression model and providing parameters to the fit function.

"""

reg = linear_model.LinearRegression()
reg.fit(df[['year']],df.pci)

reg.predict([[2020]])

reg.coef_

reg.intercept_

"""#Checking the formula y= mx+c

"""

828.46507522*2020+(-1632210.7578554575)

"""#Ploting the regression line"""

plt.xlabel('Area(sq.ft)')
plt.ylabel('Price(US$)')
plt.scatter(df.year, df.pci, color='green', marker='*')
plt.plot(df.year, reg.predict(df[['year']]), color='black')